
name: Go Build
on:
  pull_request:
    branches:
      - master

jobs:
  gobuild:
    name: Java Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Building expression service code
        run: |
          touch bazel-credentials.bzl
          touch test-util.bzl
          echo "JFROG_USERNAME=\"foo\"" >> bazel-credentials.bzl
          echo "JFROG_PASSWORD=\"bar\"" >> bazel-credentials.bzl
          echo "DISTRIBUTE_TESTING_WORKER=0" >> test-util.bzl
          echo "DISTRIBUTE_TESTING_WORKERS=1" >> test-util.bzl
          echo "OPTIMIZED_PACKAGE_TESTS=0" >> test-util.bzl
          
          echo "Building java code using bazel..."
          bazel build //...

      - name: Building product code
        run: |
          echo "Building golang product code using bazel..."
          bazel build //product/... --javacopt=' -XepDisableAllChecks'
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
